<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>C:\Users\Tom Pipe\Documents\Hexadigital\Code\Umbraco\Umbraco-CMS\src\Umbraco.Core\Attempt.cs</title>
    <script type="text/javascript" src="../js/dotcover.sourceview.js"></script>
    <link rel="stylesheet" type="text/css" href="../css/dotcover.report.css" />
  </head>
  <body>
    <pre id="content" class="source-code">
using System;

namespace Umbraco.Core
{
    /// &lt;summary&gt;
    /// Provides ways to create attempts.
    /// &lt;/summary&gt;
    public static class Attempt
    {
        /// &lt;summary&gt;
        /// Creates a successful attempt with a result.
        /// &lt;/summary&gt;
        /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
        /// &lt;param name=&quot;result&quot;&gt;The result of the attempt.&lt;/param&gt;
        /// &lt;returns&gt;The successful attempt.&lt;/returns&gt;
        public static Attempt&lt;T&gt; Succeed&lt;T&gt;(T result)
        {
            return Attempt&lt;T&gt;.Succeed(result);
        }

        /// &lt;summary&gt;
        /// Creates a failed attempt with a result.
        /// &lt;/summary&gt;
        /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
        /// &lt;param name=&quot;result&quot;&gt;The result of the attempt.&lt;/param&gt;
        /// &lt;returns&gt;The failed attempt.&lt;/returns&gt;
        public static Attempt&lt;T&gt; Fail&lt;T&gt;(T result)
        {
            return Attempt&lt;T&gt;.Fail(result);
        }

        /// &lt;summary&gt;
        /// Creates a failed attempt with a result and an exception.
        /// &lt;/summary&gt;
        /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
        /// &lt;param name=&quot;result&quot;&gt;The result of the attempt.&lt;/param&gt;
        /// &lt;param name=&quot;exception&quot;&gt;The exception causing the failure of the attempt.&lt;/param&gt;
        /// &lt;returns&gt;The failed attempt.&lt;/returns&gt;
        public static Attempt&lt;T&gt; Fail&lt;T&gt;(T result, Exception exception)
        {
            return Attempt&lt;T&gt;.Fail(result, exception);
        }

        /// &lt;summary&gt;
        /// Creates a successful or a failed attempt, with a result.
        /// &lt;/summary&gt;
        /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
        /// &lt;param name=&quot;success&quot;&gt;A value indicating whether the attempt is successful.&lt;/param&gt;
        /// &lt;param name=&quot;result&quot;&gt;The result of the attempt.&lt;/param&gt;
        /// &lt;returns&gt;The attempt.&lt;/returns&gt;
        public static Attempt&lt;T&gt; If&lt;T&gt;(bool success, T result)
        {
            return Attempt&lt;T&gt;.SucceedIf(success, result);
        }


        /// &lt;summary&gt;
        /// Executes an attempt function, with callbacks.
        /// &lt;/summary&gt;
        /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
        /// &lt;param name=&quot;attempt&quot;&gt;The attempt returned by the attempt function.&lt;/param&gt;
        /// &lt;param name=&quot;onSuccess&quot;&gt;An action to execute in case the attempt succeeds.&lt;/param&gt;
        /// &lt;param name=&quot;onFail&quot;&gt;An action to execute in case the attempt fails.&lt;/param&gt;
        /// &lt;returns&gt;The outcome of the attempt.&lt;/returns&gt;
        /// &lt;remarks&gt;Runs &lt;paramref name=&quot;onSuccess&quot;/&gt; or &lt;paramref name=&quot;onFail&quot;/&gt; depending on the
        /// whether the attempt function reports a success or a failure.&lt;/remarks&gt;
        public static Outcome Try&lt;T&gt;(Attempt&lt;T&gt; attempt, Action&lt;T&gt; onSuccess, Action&lt;Exception&gt; onFail = null)
        {
            if (attempt.Success)
            {
                onSuccess(attempt.Result);
                return Outcome.Success;
            }

            if (onFail != null)
            {
                onFail(attempt.Exception);
            }

            return Outcome.Failure;
        }

        /// &lt;summary&gt;
        /// Represents the outcome of an attempt.
        /// &lt;/summary&gt;
        /// &lt;remarks&gt;Can be a success or a failure, and allows for attempts chaining.&lt;/remarks&gt;
        public struct Outcome
        {
            private readonly bool _success;

            /// &lt;summary&gt;
            /// Gets an outcome representing a success.
            /// &lt;/summary&gt;
            public static readonly Outcome Success = new Outcome(true);

            /// &lt;summary&gt;
            /// Gets an outcome representing a failure.
            /// &lt;/summary&gt;
            public static readonly Outcome Failure = new Outcome(false);

            private Outcome(bool success)
            {
                _success = success;
            }

            /// &lt;summary&gt;
            /// Executes another attempt function, if the previous one failed, with callbacks.
            /// &lt;/summary&gt;
            /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
            /// &lt;param name=&quot;nextFunction&quot;&gt;The attempt function to execute, returning an attempt.&lt;/param&gt;
            /// &lt;param name=&quot;onSuccess&quot;&gt;An action to execute in case the attempt succeeds.&lt;/param&gt;
            /// &lt;param name=&quot;onFail&quot;&gt;An action to execute in case the attempt fails.&lt;/param&gt;
            /// &lt;returns&gt;If it executes, returns the outcome of the attempt, else returns a success outcome.&lt;/returns&gt;
            /// &lt;remarks&gt;
            /// &lt;para&gt;Executes only if the previous attempt failed, else does not execute and return a success outcome.&lt;/para&gt;
            /// &lt;para&gt;If it executes, then runs &lt;paramref name=&quot;onSuccess&quot;/&gt; or &lt;paramref name=&quot;onFail&quot;/&gt; depending on the
            /// whether the attempt function reports a success or a failure.&lt;/para&gt;
            /// &lt;/remarks&gt;
            public Outcome OnFailure&lt;T&gt;(Func&lt;Attempt&lt;T&gt;&gt; nextFunction, Action&lt;T&gt; onSuccess, Action&lt;Exception&gt; onFail = null)
            {
                return _success
                    ? Success
                    : ExecuteNextFunction(nextFunction, onSuccess, onFail);
            }

            /// &lt;summary&gt;
            /// Executes another attempt function, if the previous one succeeded, with callbacks.
            /// &lt;/summary&gt;
            /// &lt;typeparam name=&quot;T&quot;&gt;The type of the attempted operation result.&lt;/typeparam&gt;
            /// &lt;param name=&quot;nextFunction&quot;&gt;The attempt function to execute, returning an attempt.&lt;/param&gt;
            /// &lt;param name=&quot;onSuccess&quot;&gt;An action to execute in case the attempt succeeds.&lt;/param&gt;
            /// &lt;param name=&quot;onFail&quot;&gt;An action to execute in case the attempt fails.&lt;/param&gt;
            /// &lt;returns&gt;If it executes, returns the outcome of the attempt, else returns a failed outcome.&lt;/returns&gt;
            /// &lt;remarks&gt;
            /// &lt;para&gt;Executes only if the previous attempt succeeded, else does not execute and return a success outcome.&lt;/para&gt;
            /// &lt;para&gt;If it executes, then runs &lt;paramref name=&quot;onSuccess&quot;/&gt; or &lt;paramref name=&quot;onFail&quot;/&gt; depending on the
            /// whether the attempt function reports a success or a failure.&lt;/para&gt;
            /// &lt;/remarks&gt;
            public Outcome OnSuccess&lt;T&gt;(Func&lt;Attempt&lt;T&gt;&gt; nextFunction, Action&lt;T&gt; onSuccess, Action&lt;Exception&gt; onFail = null)
            {
                return _success
                    ? ExecuteNextFunction(nextFunction, onSuccess, onFail) 
                    : Failure;
            }

            private static Outcome ExecuteNextFunction&lt;T&gt;(Func&lt;Attempt&lt;T&gt;&gt; nextFunction, Action&lt;T&gt; onSuccess, Action&lt;Exception&gt; onFail = null)
            {
                var attempt = nextFunction();

                if (attempt.Success)
                {
                    onSuccess(attempt.Result);
                    return Success;
                }

                if (onFail != null)
                {
                    onFail(attempt.Exception);
                }

                return Failure;
            }
        }

    }
}
    </pre>
    <script type="text/javascript">
      highlightRanges([[17,9,17,10,1],[18,13,18,47,1],[19,9,19,10,1],[28,9,28,10,1],[29,13,29,44,1],[30,9,30,10,1],[40,9,40,10,1],[41,13,41,55,1],[42,9,42,10,1],[52,9,52,10,1],[53,13,53,58,1],[54,9,54,10,1],[68,9,68,10,1],[69,13,69,33,1],[70,13,70,14,1],[71,17,71,43,1],[72,17,72,40,1],[75,13,75,32,0],[76,13,76,14,0],[77,17,77,43,0],[78,13,78,14,0],[80,13,80,36,0],[81,9,81,10,1],[94,13,94,72,1],[99,13,99,73,1],[102,13,102,14,1],[103,17,103,36,1],[104,13,104,14,1],[120,13,120,14,1],[121,17,123,76,1],[124,13,124,14,1],[140,13,140,14,1],[141,17,143,31,1],[144,13,144,14,1],[147,13,147,14,1],[148,17,148,46,1],[150,17,150,37,1],[151,17,151,18,1],[152,21,152,47,1],[153,21,153,36,1],[156,17,156,36,1],[157,17,157,18,1],[158,21,158,47,1],[159,17,159,18,1],[161,17,161,32,1],[162,13,162,14,1]]);
    </script>
  </body>
</html>