<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>C:\Users\Tom Pipe\Documents\Hexadigital\Code\Umbraco\Umbraco-CMS\src\Umbraco.Core\Logging\LoggingTaskExtension.cs</title>
    <script type="text/javascript" src="../js/dotcover.sourceview.js"></script>
    <link rel="stylesheet" type="text/css" href="../css/dotcover.report.css" />
  </head>
  <body>
    <pre id="content" class="source-code">
using System;
using System.Threading.Tasks;

namespace Umbraco.Core.Logging
{
	internal static class LoggingTaskExtension
	{
		/// &lt;summary&gt;
		///     This task shouldn&#39;t be waited on (as it&#39;s not guaranteed to run), and you shouldn&#39;t wait on the parent task either (because it might throw an 
		///     exception that doesn&#39;t get handled). If you want to be waiting on something, use LogErrorsWaitable instead.
		/// 
		///     None of these methods are suitable for tasks that return a value. If you&#39;re wanting a result, you should probably be handling
		///     errors yourself.
		/// &lt;/summary&gt;
		public static Task LogErrors(this Task task, Action&lt;string, Exception&gt; logMethod)
		{
			return task.ContinueWith(t =&gt; LogErrorsInner(t, logMethod), TaskContinuationOptions.OnlyOnFaulted);
		}

		/// &lt;summary&gt;
		///     This task can be waited on (as it&#39;s guaranteed to run), and you should wait on this rather than the parent task. Because it&#39;s
		///     guaranteed to run, it may be slower than using LogErrors, and you should consider using that method if you don&#39;t want to wait.
		/// 
		///     None of these methods are suitable for tasks that return a value. If you&#39;re wanting a result, you should probably be handling
		///     errors yourself.
		/// &lt;/summary&gt;
		public static Task LogErrorsWaitable(this Task task, Action&lt;string, Exception&gt; logMethod)
		{
			return task.ContinueWith(t =&gt; LogErrorsInner(t, logMethod));
		}

		private static void LogErrorsInner(Task task, Action&lt;string, Exception&gt; logAction)
		{
			if (task.Exception != null)
			{
				logAction(&quot;Aggregate Exception with &quot; + task.Exception.InnerExceptions.Count + &quot; inner exceptions: &quot;, task.Exception);
				foreach (var innerException in task.Exception.InnerExceptions)
				{
					logAction(&quot;Inner exception from aggregate exception: &quot;, innerException);
				}
			}
		}
	}
}
    </pre>
    <script type="text/javascript">
      highlightRanges([[16,3,16,4,1],[17,4,17,34,1],[17,34,17,62,0],[17,62,17,103,1],[17,4,17,103,1],[18,3,18,4,1],[28,3,28,4,0],[29,4,29,34,0],[29,34,29,62,0],[29,62,29,64,0],[29,4,29,64,0],[30,3,30,4,0],[33,3,33,4,0],[34,4,34,31,0],[35,4,35,5,0],[36,5,36,123,0],[37,5,37,12,0],[37,14,37,32,0],[37,33,37,35,0],[37,36,37,66,0],[38,5,38,6,0],[39,6,39,78,0],[40,5,40,6,0],[41,4,41,5,0],[42,3,42,4,0]]);
    </script>
  </body>
</html>